window.CATEGORIES = [
  { key: 'all', title: 'الكل', icon: '✦' },
  { key: 'primary', title: 'ابتدائي', icon: '✏️' },
  { key: 'middle', title: 'متوسط', icon: '📚' },
  { key: 'secondary', title: 'ثانوي', icon: '🎓' },
  { key: 'professional', title: 'مهني', icon: '🗂️' },
];

window.PRODUCTS = [
  {
    id: 1254144835,
    category: 'primary',
    categoryLabel: 'المرحلة الابتدائية',
    title: 'ملف شامل للصفوف الأولية | للمعلم والطالب',
    shortTitle: 'ملف الصفوف الأولية',
    price: 4,
    currency: 'ر.س',
    formats: ['Word', 'PDF'],
    image: 'https://cdn.salla.sa/BreVQA/a1465d5f-5579-45e9-9dd7-33d5c3f25c49-500x333.33333333333-ENK35DbXRU9qrISxyFOxrwV28KUsS5oa6hJTlvuw.png',
    url: 'https://salla.sa/Waarq/أعالج-خطط-علاجية-للصفوف-الأولية-متجر-ورق/p1254144835',
    summary: 'منظومة عملية للصفوف الأولية تجمع التشخيص والتأسيس والعلاج والقراءة والفهم والكتابة والمتابعة.',
    bullets: [
      '12 ملفًا رقميًا بصيغتي Word وPDF.',
      'تشخيص القراءة والكتابة والفهم والمهارات الأساسية.',
      'خطط علاجية ومتابعة وقياس أثر.',
      'مناسبة للمعلم والمعلمة والطالب.',
    ],
  },
  {
    id: 1297174635,
    category: 'primary',
    categoryLabel: 'المرحلة الابتدائية',
    title: 'حزمة ورق | الصفوف العليا 4-6',
    shortTitle: 'حزمة الصفوف العليا 4-6',
    price: 29,
    currency: 'ر.س',
    formats: ['Word', 'PDF'],
    image: 'https://cdn.salla.sa/BreVQA/21fc7c67-b8cf-49c3-abc4-fe4ccf3d0bca-500x333.33333333333-svALaq9CJOT4U4U73J40Khl7eOjrAhjuDwJCK4I5.png',
    url: 'https://salla.sa/Waarq/حزمة-الصفوف-العليا-4-6-ملفات-لغة-عربية-رقمية-متجر-ورق/p1297174635',
    summary: 'ستة ملفات متكاملة للصفوف الرابع والخامس والسادس من التشخيص إلى الإتقان.',
    bullets: [
      'تشخيصي، أقرأ وأفهم، أكتب بإتقان.',
      'لغتي بمهارة، أعالج، أتقنت.',
      '12 مرفقًا: PDF + Word.',
      'جاهزة للطباعة والتعديل والمتابعة.',
    ],
  },
  {
    id: 1311224632,
    category: 'middle',
    categoryLabel: 'المرحلة المتوسطة',
    title: 'لغتي الخالدة | أول متوسط ف1',
    shortTitle: 'لغتي الخالدة | أول متوسط',
    price: 29,
    currency: 'ر.س',
    formats: ['Word', 'PDF'],
    image: 'https://cdn.salla.sa/BreVQA/fbcd8648-a411-4f7a-a31e-ad36b44b6633-418.97810218978x500-LMIEKwb3Z2C9YXTJS5s9hsJkBYjU5gkCuiNMoWRB.png',
    url: 'https://salla.sa/Waarq/لغتي-الخالدة-أول-متوسط-ف1-أوراق-واختبارات-وعلاج-ورق/p1311224632',
    summary: 'حزمة معلم لأول متوسط في الفصل الدراسي الأول: تدريب، قياس، تحليل وعلاج.',
    bullets: [
      '61 صفحة منظمة وجاهزة للطباعة.',
      '23 ورقة عمل + اختبار تشخيصي.',
      'اختبارات A/B واختبار فترة وشامل.',
      '7 خطط علاجية ومفاتيح إجابة.',
    ],
  },
  {
    id: 920385284,
    category: 'middle',
    categoryLabel: 'المرحلة المتوسطة',
    title: 'لغتي الخالدة | ثاني متوسط ف1',
    shortTitle: 'لغتي الخالدة | ثاني متوسط',
    price: 29,
    currency: 'ر.س',
    formats: ['Word', 'PDF'],
    image: 'https://cdn.salla.sa/BreVQA/953230ec-9bf8-4088-80a6-e98f9a67b7de-419.64937910884x500-3E1W564fB41HvB36NL7Ktsd9flHGjqFCNKDXlfpo.png',
    url: 'https://salla.sa/Waarq/لغتي-الخالدة-ثاني-متوسط-ف1-أوراق-واختبارات-وعلاج-ورق/p920385284',
    summary: 'حزمة تطبيق وتقويم وعلاج لثاني متوسط، مرافقة للكتاب المدرسي دون تكراره.',
    bullets: [
      '56 صفحة و24 ورقة عمل.',
      'تشخيص + اختبارات وحدات A/B.',
      'اختبار فترة واختبار شامل.',
      'تحليل نتائج و8 خطط علاجية.',
    ],
  },
  {
    id: 793250042,
    category: 'middle',
    categoryLabel: 'المرحلة المتوسطة',
    title: 'لغتي الخالدة | ثالث متوسط ف1',
    shortTitle: 'لغتي الخالدة | ثالث متوسط',
    price: 29,
    currency: 'ر.س',
    formats: ['Word', 'PDF'],
    image: 'https://cdn.salla.sa/BreVQA/e60b860b-161a-4b44-b94c-9210a1323345-419.64937910884x500-mKjzYlNe9DLxt76SOigZ3GEgVyhhTeRXMp2nLcp9.png',
    url: 'https://salla.sa/Waarq/لغتي-الخالدة-ثالث-متوسط-ف1-أوراق-واختبارات-وعلاج-ورق/p793250042',
    summary: 'أدوات صفية عملية لثالث متوسط تجمع أوراق العمل والاختبارات والتحليل والعلاج.',
    bullets: [
      '56 صفحة و24 ورقة عمل.',
      'تشخيص واختبارات A/B.',
      'اختبار فترة وشامل ومفاتيح إجابة.',
      'تحليل نتائج و8 خطط علاجية.',
    ],
  },
  {
    id: 1135140350,
    category: 'secondary',
    categoryLabel: 'المرحلة الثانوية',
    title: 'الكفايات اللغوية 1-1 | أول ثانوي',
    shortTitle: 'الكفايات اللغوية 1-1',
    price: 29,
    currency: 'ر.س',
    formats: ['Word', 'PDF', 'Excel'],
    image: 'https://cdn.salla.sa/BreVQA/19b2e531-44cf-4a6e-805d-65bec80cda98-500x333.55048859935-V1FZYMlH3rNYFN43O3cgLtYTZdjdD84Yipt3EI2d.png',
    url: 'https://salla.sa/Waarq/حقيبة-المعلم-للكفايات-اللغوية-1-1-أول-ثانوي/p1135140350',
    summary: 'حقيبة متكاملة للمعلم والطالب في الكفايات اللغوية 1-1 للفصل الدراسي الأول.',
    bullets: [
      'دليل معلم وخطط دروس.',
      'أوراق عمل واختبارات ومفاتيح إجابة.',
      'سجل متابعة آلي Excel.',
      'مذكرة تعليمية منظمة للطالب.',
    ],
  },
  {
    id: 1747372896,
    category: 'secondary',
    categoryLabel: 'المرحلة الثانوية',
    title: 'الكفايات اللغوية 2-1 | ثاني ثانوي',
    shortTitle: 'الكفايات اللغوية 2-1',
    price: 29,
    currency: 'ر.س',
    formats: ['Word', 'PDF', 'Excel'],
    image: 'https://cdn.salla.sa/BreVQA/15a16893-4052-43f4-aca6-1942f0bf86c2-500x333.55048859935-b8uuirLCBldWx5Zi26LdvdDYlsxP1GIMaDTBdKiw.png',
    url: 'https://salla.sa/Waarq/حقيبة-المعلم-للكفايات-اللغوية-2-1-ثاني-ثانوي/p1747372896',
    summary: 'منظومة تحضير وشرح وتقويم ومتابعة للمعلم مع مذكرة للفهم والمراجعة للطالب.',
    bullets: [
      'دليل تشغيل وخطط دروس.',
      'أوراق الطالب واختبارات ومفاتيح.',
      'سجل متابعة آلي Excel.',
      'مذكرة طالب للمراجعة والتدريب.',
    ],
  },
  {
    id: 140412008,
    category: 'professional',
    categoryLabel: 'أدوات مهنية',
    title: 'التشخيص والعلاج والإثراء | جميع المراحل',
    shortTitle: 'التشخيص والعلاج والإثراء',
    price: 29,
    currency: 'ر.س',
    formats: ['Word', 'PDF'],
    image: 'https://cdn.salla.sa/BreVQA/a8ac33e3-0d61-46a8-91ea-aa56354f0c03-500x500-o9hUnKLwkMGk61j2rhDorxzVqvkh9Ho2DEXUJx1l.png',
    url: 'https://salla.sa/Waarq/حقيبة-التشخيص-والعلاج-والإثراء-في-اللغة-العربية-جميع-المراحل-ورق/p140412008',
    summary: 'حقيبة مهنية لمعلم اللغة العربية تنتقل من خط الأساس إلى التدخل ثم قياس الأثر والقرار.',
    bullets: [
      '27 صفحة عملية لجميع المراحل.',
      'تحليل فجوات وتصنيف أخطاء.',
      'خطط علاج وإثراء وبنوك تدخل.',
      'متابعة وقياس أثر وتقرير ختامي.',
    ],
  },
  {
    id: 1608231952,
    category: 'professional',
    categoryLabel: 'أدوات مهنية',
    title: 'مجتمع التعلم المهني | قسم اللغة العربية',
    shortTitle: 'مجتمع التعلم المهني',
    price: 29,
    currency: 'ر.س',
    formats: ['Word', 'PDF'],
    image: 'https://cdn.salla.sa/BreVQA/10c5f683-8af1-41de-b76e-e7ebb2556b4d-500x500-FNA9iIIHodaHDyJNj7fbaKbi3IewYfRODUEhLnya.png',
    url: 'https://salla.sa/Waarq/ملف-مجتمع-التعلم-المهني-لقسم-اللغة-العربية-word-pdf-متجر-ورق/p1608231952',
    summary: 'ملف تشغيلي يحول اجتماعات قسم اللغة العربية إلى دورة عمل قائمة على البيانات والأثر.',
    bullets: [
      '31 صفحة و4 محاضر تشغيلية.',
      'تحليل ابتدائي ومتوسط وثانوي.',
      'علاج وإثراء وبحث درس ومبادرات.',
      'مؤشرات وشواهد ومراجعة ختامية.',
    ],
  },
  {
    id: 1927117004,
    category: 'professional',
    categoryLabel: 'أدوات مهنية',
    title: 'ملف الإنجاز المهني | للمعلم والمعلمة',
    shortTitle: 'ملف الإنجاز المهني',
    price: 29,
    currency: 'ر.س',
    formats: ['Word', 'PDF'],
    image: 'https://cdn.salla.sa/BreVQA/20a1d3e0-f5c9-4f0b-bcf6-747e2a8b40d0-500x500-9qjb0K1Q5OVzHLB2UoJSJ2t8Ny1yAazjqg1Itxou.png',
    url: 'https://salla.sa/Waarq/ملف-الإنجاز-المهني-الشامل-للمعلم-والمعلمة-word-pdf-متجر-ورق/p1927117004',
    summary: 'ملف إنجاز مهني شامل يربط التخطيط والتنفيذ والتقويم والتطوير والشواهد في مسار واحد.',
    bullets: [
      '106 صفحات و44 قسمًا مهنيًا.',
      'تخطيط وتقويم وتحليل أثر.',
      'علاج وإثراء وتطوير مهني.',
      'سجل أدلة وشواهد وجاهزية للتسليم.',
    ],
  },
  {
    id: 897141490,
    category: 'professional',
    categoryLabel: 'أدوات مهنية',
    title: 'الشواهد المهنية | للمعلم والمعلمة',
    shortTitle: 'الشواهد المهنية',
    price: 29,
    currency: 'ر.س',
    formats: ['Word', 'PDF'],
    image: 'https://cdn.salla.sa/BreVQA/f8fc6cb1-adbc-432d-a9e2-f793c88aa8cd-500x500-JwCPis7sbOcFNQgKRgrQ1IFmMIm4UGcXyoTweuPJ.png',
    url: 'https://salla.sa/Waarq/حقيبة-الشواهد-المهنية-للمعلم-والمعلمة-word-pdf-متجر-ورق/p897141490',
    summary: 'حقيبة لتنظيم الشواهد وتحويل الصور والمرفقات إلى أدلة مرتبطة بالممارسة والأثر.',
    bullets: [
      '20 بطاقة شاهد قابلة للتعبئة.',
      '6 نماذج استرشادية.',
      'سجل رئيس وخريطة مجالات.',
      'سلم جودة وقائمة فحص نهائية.',
    ],
  },
];

window.FEATURED_IDS = [1297174635, 1135140350, 1927117004];
